---
# Site settings
title: macOS Developer Setup
description: A powerful CLI tool for setting up macOS development environments
baseurl: "/macos-developer-setup"
url: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

# Navigation
nav_links:
  - title: Documentation
    url: /documentation
  - title: Configuration
    url: /configuration
  - title: Examples
    url: /examples
  - title: CLI
    url: /cli
  - title: Integrations
    url: /integrations

# Footer
footer:
  copyright: "© 2024 macOS Developer Setup"
