---
# Site settings
title: macOS Developer Setup
description: A comprehensive tool for setting up macOS development environments
baseurl: "/macos-developer-setup"
url: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/yourusername/macos-developer-setup

# Navigation
nav_links:
  - title: Documentation
    url: /documentation
  - title: Configuration
    url: /configuration
  - title: Examples
    url: /examples
  - title: CLI
    url: /cli
  - title: Integrations
    url: /integrations

# Footer
footer:
  copyright: "© 2024 macOS Developer Setup"
