# Site settings
title: zapz
description: The zero-dependency macOS development environment setup tool
url: "https://corbanb.github.io/zapz"
baseurl: "/zapz"

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Navigation
nav_links:
  - title: Documentation
    url: /docs
  - title: GitHub
    url: https://github.com/corbanb/zapz

# GitHub metadata
github:
  is_project_page: true
  repository_url: https://github.com/corbanb/zapz
  owner_name: corbanb
  repository_name: zapz 