---
name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Homebrew Updates
        run: |
          brew update
          brew outdated

      - name: Create PR if Updates Available
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'chore: update homebrew dependencies'
          body: 'Updates available for homebrew packages'
          branch: 'chore/update-dependencies'
