name: Installation Test

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:

jobs:
  test-install:
    runs-on: macos-latest
    permissions:
      checks: write
      pull-requests: write
    strategy:
      matrix:
        os-version: [monterey, ventura, sonoma]
    steps:
      - name: Clean Environment
        id: clean
        run: |
          rm -rf ~/.local/bin/zapz
          rm -rf ~/.zapz*

      - name: Test Installation
        id: install
        run: |
          curl -fsSL https://raw.githubusercontent.com/corbanb/zapz/main/install.sh | bash
          zapz --version

      - name: Test Basic Setup
        id: setup
        run: zapz --test

      - name: Report Status
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const success = context.job === 'test-install' &&
              steps.clean.outcome === 'success' &&
              steps.install.outcome === 'success' &&
              steps.setup.outcome === 'success';

            const message = success
              ? '✅ Installation test passed!'
              : '❌ Installation test failed. Please check the logs.';

            if (context.issue.number) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            }
