name: Code Quality

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Create config directory
        run: |
          mkdir -p ~/.config/yamllint
          cp .yamllint ~/.config/yamllint/config

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .yamllint
          strict: false

      - name: Report Status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const run_id = context.runId;

            core.info(`Run ID: ${run_id}`);

            if (!run_id) {
              core.warning('No run ID found, skipping status report');
              return;
            }

            try {
              const jobs = await github.rest.actions.listJobsForWorkflowRun({
                owner,
                repo,
                run_id,
              });

              const job = jobs.data.jobs.find(j => j.name === 'lint');
              if (!job) {
                core.warning('Could not find lint job');
                return;
              }

              const conclusion = job.conclusion || 'pending';
              core.info(`Job conclusion: ${conclusion}`);

              if (conclusion === 'failure') {
                core.setFailed('Lint checks failed');
              }
            } catch (error) {
              core.warning(`Error getting job status: ${error.message}`);
            }
