name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create config directory
        run: mkdir -p config
      
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          severity: warning
          extra_args: '-x'
          check_together: true
          
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: |
            config/
            .github/workflows/
          config_file: .yamllint
          
      - name: Check Script Formatting
        run: |
          brew install shfmt
          shfmt -d .