name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Create config directory
        run: mkdir -p config

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          severity: warning
          check_together: true

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: |
            config/
            .github/workflows/
          config_file: .yamllint

      - name: Check Script Formatting
        run: |
          brew install shfmt
          shfmt -d .

      - name: Report Status
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const { conclusion } = context.payload.check_run;
            const message = conclusion === 'success'
              ? '✅ All checks passed!'
              : '❌ Some checks failed. Please fix the issues above.';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
