name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Tests
      run: |
        chmod +x test/test.sh
        ./test/test.sh
    
    - name: Run Installation Tests
      run: |
        chmod +x test/test_install.sh
        ./test/test_install.sh