name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        brew install shellcheck shfmt

    - name: Run Tests
      id: tests
      run: |
        chmod +x test/test.sh
        ./test/test.sh

    - name: Run Installation Tests
      id: install_tests
      run: |
        chmod +x test/test_install.sh
        ./test/test_install.sh

    - name: Report Status
      uses: actions/github-script@v6
      if: always()
      with:
        script: |
          const success = context.job === 'test' &&
            context.steps.tests.outcome === 'success' &&
            context.steps.install_tests.outcome === 'success';

          const message = success
            ? '✅ All tests passed!'
            : '❌ Some tests failed. Please check the logs.';

          if (context.issue.number) {
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
          }
